nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

nmHoistingLimits: workspaces

npmRegistryServer: 'https://registry.yarnpkg.com/'

npmScopes:
  connect:
    npmRegistryServer: 'https://repo.br.hmheng.io/artifactory/api/npm/content-engg-npm/'
    npmAuthToken: 'eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJfQXNqTU5fd0N6dVloelhrNHJ5b0xtV1FDbjN6MTZxNWNKUkM5NXpyTGpJIn0.eyJzdWIiOiJqZi1hcnRpZmFjdG9yeUBjZTk5MmQ0Yi0xMDVlLTRlYTQtYTQ5NC04ZDkzNWJlMjhhMzFcL3VzZXJzXC9hZGFtZWttIiwic2NwIjoibWVtYmVyLW9mLWdyb3VwczoqIiwiYXVkIjoiamYtYXJ0aWZhY3RvcnlAY2U5OTJkNGItMTA1ZS00ZWE0LWE0OTQtOGQ5MzViZTI4YTMxIiwiaXNzIjoiamYtYXJ0aWZhY3RvcnlAY2U5OTJkNGItMTA1ZS00ZWE0LWE0OTQtOGQ5MzViZTI4YTMxXC91c2Vyc1wvYWRhbWVrbSIsImlhdCI6MTcwODQ1OTQ5MSwianRpIjoiN2IzMWI2NDctZDAxMy00MTNmLTkyNjAtODdkMDBlYTNjOGJlIn0.oKwV63C23z6NucLVyeQ8TbQ27PVyBF4PabGigbsRz7s3WMF-0nACe-EK3o-2tEFN1KLHXY-t8qfLjhNKNm_fRFCV4ESs8wQ1NIfeND_MVekZcmv38ZNAYHwNt1m7bdYvEM6YlWXH5zVCaaIbIDbRc1zbsYTk6TDDgOx6RA8R13VHqOe141-_NAleWSpKW3ISJPDJ76wlY8kKOaOsZaNCHh8hhkgcvEKppJab4dK8NPMhSl-iIs4P9wB4kMLUqAbLIvtqin_aS7Zh28t90eLmTZcN-4J0kpitftAbIurxVNm0_tE8OgRdpj9GL3yYwM9pXLPhzC-o_GNKwaSXmv7kcw'
