import Accordion from './components/Accordion/Accordion';
import Blockquote from './components/Blockquote/Blockquote';
import Button from './components/Button/Button';
import ButtonMenu from './components/ButtonMenu/ButtonMenu';
import ButtonRive from './components/ButtonRive/ButtonRive';
import ButtonSplit from './components/ButtonSplit/ButtonSplit';
// import Card from './components/Card/Card';
import Checkbox from './components/Checkbox/Checkbox';
import Chip from './components/Chip/Chip';
import Divider from './components/Divider/Divider';
import FigCaption from './components/FigCaption/FigCaption';
import Figure from './components/Figure/Figure';
import Footer from './components/Footer/Footer';
import Grid from './components/Grid/Grid';
import GridItem from './components/GridItem/GridItem';
import Header from './components/Header/Header';
import Icon from './components/Icon/Icon';
import Image from './components/Image/Image';
import InputBox from './components/InputBox/InputBox';
import InputText from './components/InputText/InputText';
import List from './components/List/List';
import MultipleChoiceQuestionImage from './components/MultipleChoiceQuestion/MultipleChoiceQuestionImage';
import Paper from './components/Paper/Paper';
import Pill from './components/Pill/Pill';
import ProgressBar from './components/ProgressBar/ProgressBar';
import RiveEngine from './components/RiveEngine/RiveEngine';
import RiveSimple from './components/RiveSimple/RiveSimple';
import SelectBox from './components/SelectBox/SelectBox';
import Sidebar from './components/Sidebar/Sidebar';
import SingleBlockquote from './components/SingleBlockquote/SingleBlockquote';
import SingleImage from './components/SingleImage/SingleImage';
import Stack from './components/Stack/Stack';
import Textarea from './components/Textarea/Textarea';
import Timer from './components/Timer/Timer';
import Typography from './components/Typography/Typography';

export interface ConnectDesignSystem {
  Accordion: typeof Accordion;
  Blockquote: typeof Blockquote;
  Button: typeof Button;
  ButtonMenu: typeof ButtonMenu;
  ButtonRive: typeof ButtonRive;
  ButtonSplit: typeof ButtonSplit;
  // Card: typeof Card;
  Checkbox: typeof Checkbox;
  Chip: typeof Chip;
  Divider: typeof Divider;
  FigCaption: typeof FigCaption;
  Figure: typeof Figure;
  Footer: typeof Footer;
  Grid: typeof Grid;
  GridItem: typeof GridItem;
  Header: typeof Header;
  Icon: typeof Icon;
  Image: typeof Image;
  InputBox: typeof InputBox;
  InputText: typeof InputText;
  List: typeof List;
  MultipleChoiceQuestion: typeof MultipleChoiceQuestion;
  MultipleChoiceQuestionImage: typeof MultipleChoiceQuestionImage;
  Paper: typeof Paper;
  Pill: typeof Pill;
  ProgressBar: typeof ProgressBar;
  RiveEngine: typeof RiveEngine;
  RiveSimple: typeof RiveSimple;
  SelectBox: typeof SelectBox;
  Sidebar: typeof Sidebar;
  SingleBlockquote: typeof SingleBlockquote;
  SingleImage: typeof SingleImage;
  Stack: typeof Stack;
  Textarea: typeof Textarea;
  Timer: typeof Timer;
  Typography: typeof Typography;
}

declare module 'connect-design-system' {
  export default ConnectDesignSystem;
}
