export type IconId = 
  'loader'|
  'add'|
  'arrow-down'|
  'arrow-up'|
  'circle-cross'|
  'circle-tick'|
  'correct-six-twelve'|
  'cross-xs'|
  'incorrect-six-twelve'|
  'mic'|
  'pause'|
  'play'|
  'shown-correct-six-twelve'|
  'tick'|
  'tick-xs'|
  'correct'|
  'incorrect'|
  'shown-correct'|
  'color'|
  'counter-one'|
  'draw-outline'|
  'draw-size-one'|
  'draw-size-three'|
  'draw-size-two'|
  'line-arrow'|
  'line-dashed'|
  'line'|
  'lines-outline'|
  'redo'|
  'undo'|
  'circle-outline'|
  'circle'|
  'shapes-outline'|
  'rectangle-outline'|
  'rectangle'|
  'triangle-outline'|
  'special-shapes-one'|
  'triangle'|
  'special-shapes-three'|
  'special-shapes-two'|
  'stamps-measure-outline'|
  'stamps-counter-outline'|
  'stamps-special-shapes-outline'|
  'add'|
  'check'|
  'close'|
  'collapse'|
  'desmos'|
  'expand'|
  'flag'|
  'groupActivity'|
  'groupActivityVariant'|
  'info'|
  'pause'|
  'play'|
  'reduce'|
  'renew'|
  'soundMeter'|
  'stop'|
  'stopwatch'|
  'studentPicker'|
  'timer'
;
 // To generate lists run 'Node src/utils/sprite-ids.js'