export type IconId = 
  'add'|
  'align-center'|
  'align-left'|
  'align-right'|
  'arrow-down'|
  'arrow-up'|
  'arrow-left'|
  'arrow-left-dbl'|
  'arrow-right'|
  'arrow-right-dbl'|
  'audio-description'|
  'audio-next'|
  'audio-pause'|
  'audio-play'|
  'audio-previous'|
  'audio-replay'|
  'bold'|
  'change'|
  'circle-cross'|
  'circle-tick'|
  'closed-captioning'|
  'correct-six-twelve'|
  'cross-xs'|
  'delete'|
  'download'|
  'erase'|
  'flip'|
  'glyphs'|
  'help'|
  'incorrect-six-twelve'|
  'info'|
  'italic'|
  'light-bulb'|
  'list-bullet'|
  'list-number'|
  'maximize'|
  'menu-grid'|
  'mic'|
  'minimize'|
  'more-horiz'|
  'more-vert'|
  'move'|
  'open'|
  'pause'|
  'pdf'|
  'play'|
  'redo'|
  'reload'|
  'save'|
  'save-as'|
  'settings'|
  'shown-correct-six-twelve'|
  'size'|
  'star'|
  'star-outline'|
  'text-label'|
  'tick'|
  'tick-xs'|
  'transcript'|
  'underline'|
  'upload'|
  'video-clip'|
  'vocabulary'|
  'volume-high'|
  'volume-low'|
  'volume-mid'|
  'volume-mute'|
  'correct'|
  'incorrect'|
  'shown-correct'|
  'close'|
  'text'|
  'calendar'|
  'print'|
  'image'|
  'clock'|
  'color'|
  'counter-one'|
  'draw-outline'|
  'draw-size-one'|
  'draw-size-three'|
  'draw-size-two'|
  'line-arrow'|
  'line-dashed'|
  'line'|
  'lines-outline'|
  'placeholder'|
  'redo'|
  'shapes-circle-outline'|
  'shapes-circle'|
  'shapes-outline'|
  'shapes-rectangule-outline'|
  'shapes-rectangle'|
  'shapes-triangle-outline'|
  'special-shapes-one'|
  'shapes-triangle'|
  'special-shapes-three'|
  'special-shapes-two'|
  'stamps-counter-outline'|
  'stamps-measures-outline'|
  'stamps-special-shapes-outline'
;
 // To generate lists run 'Node src/utils/sprite-ids.js'